name: Pipeline
on: 
  push: 
    branches:
     - '*'
jobs:

  todos:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v2
      - run: make check-todos
  conflicts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: make check-conflicts
  gitflow:
    runs-on: ubuntu-latest
    if: "!contains(github.ref, 'master')"
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: make check-master

  lint:
    runs-on: ubuntu-latest
    needs: [todos, conflicts]
    steps:
      - uses: actions/checkout@v2
      - run: make lint
  
  # scan: @TODO:
  #   runs-on: ubuntu-latest
  #   needs: [todos, conflicts]
  #   steps:
  #     - uses: actions/checkout@v2
  #     - run: make scan

  build:
    runs-on: ubuntu-latest
    needs: [todos, conflicts]
    steps:
      - uses: actions/checkout@v2
      - run: make images
