name: Pipeline
on: 
  push: 
    branches:
     - '*'
jobs:

  todos:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v2
      - run: make check-todos
  conflicts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: make check-conflicts
  gitflow:
    runs-on: ubuntu-latest
    if: "!contains(github.ref, 'master')"
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: make check-master
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: make lint
  
  build:
    runs-on: ubuntu-latest
    needs: [todos, conflicts, linter]
    env:
      JOB_IMAGE: egnd/proxy
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - name: Build tor image
        uses: docker/build-push-action@v2
        with:
          context: tor
          platforms: linux/amd64,linux/arm64,linux/arm
          push: false
          tags: ${{env.JOB_IMAGE}}:tor-local
          cache-from: ${{env.JOB_IMAGE}}:tor-latest
      # - name: Scan tor image
      #   uses: azure/container-scan@v0
      #   with:
      #     image-name: ${{env.JOB_IMAGE}}:tor-local
      # - name: Check tor image
      #   run: docker run --rm ${{env.JOB_IMAGE}}:tor-local --version
      - name: Build privoxy image
        uses: docker/build-push-action@v2
        with:
          context: privoxy
          platforms: linux/amd64,linux/arm64,linux/arm
          push: false
          tags: ${{env.JOB_IMAGE}}:privoxy-local
          cache-from: ${{env.JOB_IMAGE}}:privoxy-latest
      # - name: Scan privoxy image
      #   uses: azure/container-scan@v0
      #   with:
      #     image-name: ${{env.JOB_IMAGE}}:privoxy-local
      # - name: Check privoxy image
      #   run: docker run --rm ${{env.JOB_IMAGE}}:privoxy-local --version
