name: Publish

on:
  push:
    tags:
      - 'v*'

jobs:

  build-tor:
    runs-on: ubuntu-latest
    env:
      JOB_IMAGE: egnd/proxy
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - uses: docker/build-push-action@v2
        with:
          context: tor
          platforms: linux/amd64,linux/arm64,linux/arm
          push: true
          tags: ${{env.JOB_IMAGE}}:tor-latest,${{env.JOB_IMAGE}}:tor-${{env.IMG_VERSION}}
          cache-from: ${{env.JOB_IMAGE}}:tor-latest
      - uses: azure/container-scan@v0
        with:
          image-name: ${{env.JOB_IMAGE}}:tor-${{env.IMG_VERSION}}

  build-privoxy:
    runs-on: ubuntu-latest
    env:
      JOB_IMAGE: egnd/proxy
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - uses: docker/build-push-action@v2
        with:
          context: privoxy
          platforms: linux/amd64,linux/arm64,linux/arm
          push: true
          tags: ${{env.JOB_IMAGE}}:privoxy-latest,${{env.JOB_IMAGE}}:privoxy-${{env.IMG_VERSION}}
          cache-from: ${{env.JOB_IMAGE}}:privoxy-latest
      - uses: azure/container-scan@v0
        with:
          image-name: ${{env.JOB_IMAGE}}:privoxy-${{env.IMG_VERSION}}
